### ISSUE TITLE
Как лучше дополнять правила?

### ISSUE THREAD

**Issue by gambala** [estum/russian_inflect#2]
Живая ситуация - "Севастополь" склоняется некорректно (Севастополи в пред. падеже). Каким образом лучше внести коррективы в правила?
- Можно ли разместить rules.yml у себя в проекте и дополнять быстро, не вмешиваясь в гем?
- Как лучше дополнить, через исключение или суффикс?
- Как добавлять исключения в yml файл? (какая иерархия в yml?)
- Как лучше сконтрибьютить дополнения, если их станет достаточно много?

**Comment by estum** [comment]
@gambala 

Я довольно давно не работал над этим гемом. Сейчас пробежался по коду, чтобы освежить память, в итоге появилось несколько идей по абстрагированию API и улучшению структуры правил.

Всегда можно (и нужно!) форкнуть или расширить подклассами, в свободную минутку постараюсь замутить какую-нибудь кастомизацию.

По поводу текущих правил. Сами правила можно подглядеть в [Викисловаре](https://ru.wiktionary.org/wiki/Викисловарь:Шаблоны_словоизменений/Существительные/Мужской_род). Допустим для  слова "Севастополь" — можно добавить правила в `rules.yml` с окончанием "ль":

```yaml
# мужской род
second_group:
  # существительное
  noun:
    suffixes:
      -
        test: [тель]
        mods: [-я, -ю, -я, -ем, -е]
      -
        test: [ль]
        mods: [-я, -ю, ., -ем, -е]
      # стоит добавлять перед более общим случаем
      -
        test: [ь]
        # т.д.
```

Еще нужно было бы вынести правила определения рода из метода  `RussianInflect.detect_case_group` чтобы было проще дополнять их. Сейчас там очень обобщенные случаи и  "Севастополь" попадает в third_group, если не указать напрямую RussianInflect.new("Севастополь", group: 2).

В исключения добавляются только слова целиком, к которым не подходит ни один шаблон, например какие-нибудь заимствования или имена собственные.
